version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: cd laradock && docker-compose build nginx workspace php-fpm
      - run:
          name: test
          command: |
            cd laradock && \
              docker-compose run workspace '\
              php artisan key:generate &&
              /var/www/vendor/bin/phpunit'
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: "build docker image"
          command: echo "OK"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
