version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: cd laradock && docker-compose build workspace
      - run:
          name: composer
          command: |
            cd laradock && \
              docker-compose run workspace composer install --no-dev
      - run:
          name: npm
          command: |
            cd sample && \
              npm install && npm run prod
      - run:
          name: make zip
          command: |
            cd sample && \
              zip -r -q ../deploy.zip -r * .[^.]*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
